# Generated by Django 4.0.6 on 2022-07-18 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='auth',
        ),
    ]
