# Generated by Django 4.0.6 on 2022-07-18 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationapp', '0002_rename_author_book_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='relationapp.author'),
        ),
    ]
